import type {Metadata} from 'next'
import {Geist, Geist_Mono, Poppins, Nunito_Sans} from 'next/font/google'
import Footer from '@/components/footer'
import Header from '@/components/header'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const poppins = Poppins({subsets: ['latin'], variable: '--font-poppins', weight: ['400', '600', '700']})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

const nunitoSans = Nunito_Sans({
  variable: '--font-nunito-sans',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} ${nunitoSans.variable} antialiased`}
      >
        <div className="flex flex-col min-h-screen bg-white">
          <Header />
          <div className="flex-1">
            <main>{children}</main>
          </div>
          <Footer />
        </div>
      </body>
    </html>
  )
}
